### ISSUE TITLE
Signup is just a POC, needs fleshing out

### ISSUE THREAD

**Issue by BellJohn** [BellJohn/DC2060#6]
Signup is currently only a proof of concept. We need to add appropriate fields and validation on input.
Also, need to handle hashing and salting of passwords and store them separately to the users table. Then we can have expiry etc.

**Comment by morganjess** [comment]
@BellJohn I have made changes to the sign up page, it is failing to create an account because it is throwing the exception about duplicate usernames but this isn't the actual reason I think that is just the only exception it sees. It passes all the sign up validation but when it goes to create the user object it is failing - could be to do with this - SqlExceptionHelper - Field 'USERS_FIRSTNAME
